on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'
    - '**.bsdesign'
    - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Lint HTML files
      uses: chabad360/htmlproofer@master
      with:
          directory: "./"
          # The directory to scan
          arguments: --check-favicon --check-img-http --enforce-https --disable-external --alt-ignore https://www.facebook.com/tr?id=154907775729568&ev=PageView&noscript=1
          # The arguments to pass to HTMLProofer
            
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"

    - name: Install stylelint
      run: npm init && npm install --save-dev stylelint stylelint-config-standard

    - name: Get CSS linter
      uses: xt0rted/stylelint-problem-matcher@v1

    - run: npm ci
      working-directory: "assets/css"
    - run: npm test
      working-directory: "assets/css"

    - name: Deploy with Netlify
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
